description: "This Yeager Workflow fetches announcements from specified channels and\
  \ uses GPT\nto filter relevant messages before sending them to a specified user\
  \ through\ndirect messages. The workflow is composed of the following steps:\n-\
  \ Monitoring a list of channel IDs.\n- Sending any detected messages in these channels\
  \ to GPT for filtering.\n- Delivering the filtered messages to a user's direct messages.\n\
  \nIOs - \n  - InputAnnouncementModel: A BaseModel with these fields:\n      - channels_ids:\
  \ List of channel IDs to monitor.\n      - user_id: The ID of the user to send the\
  \ filtered messages to.\n      - gpt_key: The OpenAI API key needed for GPT access.\n\
  \      - discord_bot_token: The Discord bot token to interact with the Discord API.\n\
  \n  - OutputDirectMessageModel: A BaseModel with these fields:\n      - sent_messages:\
  \ \n        A list of dictionaries containing:\n          - channel: The ID of the\
  \ announcement channel where the message was posted.\n          - content: The original\
  \ content of the filtered message.\n"
input-class: InputAnnouncementModel
name: GPTFilteredAnnouncementDM
output-class: OutputDirectMessageModel
parameters: {}
